### PR TITLE
Change text: to plain: for rails 5

### PR DESCRIPTION
**Pull request by kreynolds**
Small change to handle deprecation notices now in rails 5

### CODE REVIEW

**Comment by mattwigham** [comment]
@kreynolds KELLEY!

**Comment by kreynolds** [comment]
@mattwigham I know right? Blast from the past!

img_0058

**Comment by mattwigham** [comment]
@kreynolds so big!

screen shot 2016-09-21 at 2 35 18 pm

**Comment by biscuitvile** [comment]
@kreynolds Yooooo! I hope all is well, dude! The girls look so big oh my god!

**Comment by kreynolds** [comment]
@biscuitvile All is well! Katie already knows more about iPads than I do and Emily wants to build robots. I'm in serious trouble ..

**Comment by kreynolds** [comment]
@mattwigham Lovely! Who needs Slack? We have github comments!

**Pull request merged**
